services:
  cf_picture_compare:
    container_name: cf_picture_compare
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: unless-stopped
